api/urls.py
from django.urls import path
from api import views
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import ObtainAuthToken

router=DefaultRouter()
router.register("cakes",views.CakesView,basename="cakes")
router.register("carts",views.CartsView,basename="carts")
router.register("orders",views.OrdersView,basename="orders")

urlpatterns=[

path("register/",views.UserCreationView.as_view()),
path("token/",ObtainAuthToken.as_view())

]+router.urls

cakebox/urls.py
from django.urls import path
from cakebox.views import SignupView,SigninView,CategoryCreateView,remove_category,\
CakecreateView,CakelistView,CakeUpdateView,remove_cakeview,CakeVarientCreateView,\
CakeDetailView,CakevarientUpdateView,remove_varient,CakeofferView,remove_offer,signout_view,IndexView


urlpatterns=[
    path("register/",SignupView.as_view(),name="signup"),
    path("",SigninView.as_view(),name="signin"),
    path("categories/add",CategoryCreateView.as_view(),name="add-category"),
    path("categories/<int:pk>/remove",remove_category,name="remove-category"),
    path("cakes/add",CakecreateView.as_view(),name="cake-add"),
    path("cakes/all",CakelistView.as_view(),name="cake-list"),
    path("cakes/<int:pk>/change",CakeUpdateView.as_view(),name="cake-change"),
    path("cakes/<int:pk>/remove",remove_cakeview,name="cake-remove"),
    path("cakes/<int:pk>/varients/add",CakeVarientCreateView.as_view(),name="add-varient"),
    path("cakes/<int:pk>/",CakeDetailView.as_view(),name="cake-detail"),
    path("cakes/<int:pk>/varients/change",CakevarientUpdateView.as_view(),name="update-varient"),
    path("cakes/<int:pk>,varients/remove",remove_varient,name="remove-varient"),
    path("cakes/<int:pk>/varients/offers/add",CakeofferView.as_view(),name="offer-varient"),
    path("offers/<int:pk>/remove",remove_offer,name="remove-offer"),
    path("logout/",signout_view,name="signout"),
    path("index",IndexView.as_view(),name='index'),




]

cakeboxproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/",include("api.urls")),

    path("",include("cakebox.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cakebox/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.



class User(AbstractUser):

    phone=models.CharField(max_length=100,unique=True)
    address=models.CharField(max_length=200)


class Category(models.Model):

    name=models.CharField(max_length=200,unique=True)
    is_available=models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
class Cakes(models.Model):
    name=models.CharField(max_length=200)


    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    
    options=(
        ('chocolate','chocolate'),
        ('vancho','vancho'),
        ('redbee','redbee'),
        ('black forest','black forest'),
        ('red velvet','red velvet'),
        ('cheese cake','cheese cake'),
        ('rainbow cake','rainbow cake'),
        ('coffee cake','coffee cake'),
        ('non-alcoholic','non-alcoholic'),
        ('butter  scotch','butter scotch'),
        ('vanilla','vanilla'),
        ('mango','mango'),
        ('pineapple','pineapple'),
        ('dates','dates'),
        ('plum','plum'),
        ('dry-fruits','dry-fruits'),
        ('mixed-fruits','mixed-fruits'),
        ('blueberry','blueberry'),
        ('strawberry','strawberry')
    )
    flavour=models.CharField(max_length=200,choices=options,default="chocolate")

    image=models.ImageField(upload_to="images")
    
    @property
    def varients(self):
        qs=self.cakevarients_set.all()
        return qs


    def __str__(self):
        return self.name

class CakeVarients(models.Model):
    price=models.PositiveIntegerField()
    
    options=(
        (".5kg",".5kg"),
        ("1kg","1kg"),
        ("2kg","2kg"),
        ("3kg","3kg"),
        ("4kg","4kg"),
        ("5kg","5kg")
       
    )

    size=models.CharField(max_length=200,choices=options,default="1kg")
    option=(
        ("round","round"),
        ("square","square"),
        ("rectangle","rectangle"),
        ("heart","heart"),
        ("cylindrical","cylindrical"),
        ("tier","tier")


    )
    shape=models.CharField(max_length=200,choices=option,default="round")
    cake=models.ForeignKey(Cakes,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.cake.name

class Offers(models.Model):
    cakevarient=models.ForeignKey(CakeVarients,on_delete=models.CASCADE)
    price=models.PositiveIntegerField()
    start_date=models.DateTimeField()
    due_date=models.DateTimeField()


class Carts(models.Model):
    cakevarient=models.ForeignKey(CakeVarients,on_delete=models.DO_NOTHING)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    options=(
        ("in-cart","in-cart"),
        ("order-placed","order-placed"),
        ("cancelled","cancelled")
    )

    status=models.CharField(max_length=200,choices=options,default="in-cart")
    date=models.DateTimeField(auto_now_add=True)


class Orders(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    cakevarient=models.ForeignKey(CakeVarients,on_delete=models.CASCADE)
    options=(
      
        ("order-placed","order-placed"),
        ("cancelled","cancelled"),
        ("dispatced","dispatched"),
        ("in-transit","in-transit"),
        ("delivered","delivered")
    )
    status=models.CharField(max_length=200,choices=options,default="order-placed")
    orderd_date=models.DateTimeField(auto_now_add=True)
    expected_date=models.DateField(null=True)
    address=models.CharField(max_length=200)

from django.core.validators import MinValueValidator,MaxValueValidator

class Reviews(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    cake=models.ForeignKey(Cakes,null=True,on_delete=models.SET_NULL)
    rating=models.PositiveIntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])
    comment=models.CharField(max_length=300)

cakebox/forms.py
from django import forms
from cakebox.models import User,Category,Cakes,CakeVarients,Offers
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=["username","email","password1","password2","phone","address"]

class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)

class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model=Category
        fields="__all__"

class CakeAddForm(forms.ModelForm):
    class Meta:
        model=Cakes
        fields="__all__"


class CakeVarientForm(forms.ModelForm):
    class Meta:
        model=CakeVarients
        exclude=("cake",)


class CakeOfferForm(forms.ModelForm):
    class Meta:
        model=Offers
        exclude=("Cake_variant",)
        widgets={
            "start_date":forms.DateInput(attrs={"type":"date"}),
            "due_date":forms.DateInput(attrs={"type":"date"})
        }

cakebox/views.py
from django.shortcuts import render,redirect
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.db import models
from django.urls import reverse_lazy,reverse
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.utils.decorators import method_decorator
from django.views.generic import View,CreateView,FormView,ListView,UpdateView,DetailView,TemplateView

from cakebox.models import User,Category,Cakes,CakeVarients,Offers
from cakebox.forms import RegistrationForm,LoginForm,CategoryCreateForm,CakeAddForm,\
    CakeVarientForm,CakeOfferForm

# Create your views here.

def signin_required(fn):

    def wrapper(request,*args,**kwargs):
        if not request.user.is_authenticated:
            messages.error(request,"invalid session...")
            return redirect("signin")
        else:
            return fn(request,*args,**kwargs)
    return wrapper

def is_admin(fn):

    def wrapper(request,*args,**kwargs):
        if not request.user.is_superuser:
            messages.error(request,"permision denied for current user...")
            return redirect("signin")
        else:
            return fn(request,*args,**kwargs)
        
    return wrapper

decs=[signin_required,is_admin]

class IndexView(TemplateView):
    template_name="cakebox/index.html"


class SignupView(CreateView):
    template_name="cakebox/reg.html"
    model=User
    form_class=RegistrationForm
    success_url=reverse_lazy("signin")

    def form_valid(self,form):
        messages.success(self.request,"account created")
        return super().form_valid(form)
    def form_invalid(self,form):
        messages.error(self.request,"failed to create account")
        return super().form_invalid(form)
    

class SigninView(FormView):
    template_name="cakebox/login.html"
    form_class=LoginForm

    def post(self,request,*args,**kwargs):
        form=LoginForm(request.POST)

        if form.is_valid():
            uname=form.cleaned_data.get("username")
            pwd=form.cleaned_data.get("password")
            usr=authenticate(username=uname,password=pwd)
            if usr:
                login(request,usr)
                messages.success(request,"login successfully...")
                return redirect("index")
            else:
                messages.error(request,"login failed...try again..")
                return render(request,self.template_name,{"form":form})


@method_decorator(decs,name="dispatch")
class CategoryCreateView(CreateView,ListView):
    template_name="cakebox/cat_add.html"
    form_class=CategoryCreateForm
    model=Category
    context_object_name="categories"
    success_url=reverse_lazy("add-category")

    def form_valid(self, form):
        messages.success(self.request,"category added...")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request,"category adding failed...")
        return super().form_invalid(form)
    
    def get_queryset(self):
        return Category.objects.filter(is_available=True)
    
@signin_required
@is_admin
def remove_category(request,*args,**kwargs):
    id=kwargs.get("pk")
    Category.objects.filter(id=id).update(is_available=False)
    messages.success(request,"category removed...")
    return redirect("add-category")


@method_decorator(decs,name="dispatch")
class CakecreateView(CreateView):
    template_name="cakebox/cake_add.html"
    model=Cakes
    form_class=CakeAddForm
    success_url=reverse_lazy("cake-list")

    def form_valid(self, form):
        messages.success(self.request,"cake has been added...")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request,"cake adding failed...")
        return super().form_invalid(form)
    

@method_decorator(decs,name="dispatch")
class CakelistView(ListView):
    template_name="cakebox/cake_list.html"
    model=Cakes
    context_object_name="cakes"


@method_decorator(decs,name="dispatch")
class CakeUpdateView(UpdateView):
    template_name="cakebox/cake_edit.html"
    model=Cakes
    form_class=CakeAddForm
    success_url=reverse_lazy("cake-list")

    def form_valid(self, form):
        messages.success(self.request,"cake updated...")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request,"cake updating failed...")
        return super().form_invalid(form)
    
@signin_required
@is_admin
def remove_cakeview(request,*args,**kwargs):
    id=kwargs.get("pk")
    Cakes.objects.filter(id=id).delete()
    messages.success(request,"item removed...")
    return redirect("cake-list")


@method_decorator(decs,name="dispatch")
class CakeVarientCreateView(CreateView):
    template_name="cakebox/cakevar_add.html"
    model=CakeVarients
    form_class=CakeVarientForm
    success_url=reverse_lazy("cake-list")

    def form_valid(self, form):
        id=self.kwargs.get("pk")
        obj=Cakes.objects.get(id=id)
        form.instance.cake=obj
        messages.success(self.request,"varient has been added...")
        return super().form_valid(form)
    

@method_decorator(decs,name="dispatch")
class CakeDetailView(DetailView):
    template_name="cakebox/cake_detail.html"
    model=Cakes
    context_object_name="cake"


@method_decorator(decs,name="dispatch")
class CakevarientUpdateView(UpdateView):
    template_name="cakebox/cakevar_edit.html"
    model=CakeVarients
    form_class=CakeVarientForm

    def form_valid(self, form):
        messages.success(self.request,"cake varient updated...")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request,"cake varient updating failed...")
        return super().form_invalid(form)
    
    def get_success_url(self):
        id=self.kwargs.get("pk")
        cake_varient_object=CakeVarients.objects.get(id=id)
        cake_id=cake_varient_object.Cake.id

        return reverse("cake-detail",kwargs={"pk":cake_id})
    

@signin_required
@is_admin
def remove_varient(request,*args,**kwargs):
    id=kwargs.get("pk")
    CakeVarients.objects.filter(id=id).delete()
    messages.success(request,"item removed...")
    return redirect("cake-list")


@method_decorator(decs,name="dispatch")
class CakeofferView(CreateView):
    template_name="cakebox/ck_offer.html"
    model=Offers
    form_class=CakeOfferForm
    success_url=reverse_lazy("cake-list")

    def form_valid(self, form):
        id=self.kwargs.get("pk")
        obj=CakeVarients.objects.get(id=id)
        form.instance.cakevarient=obj

        messages.success(self.request,"offer has been added...")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request," offer close...")
        return super().form_invalid(form)
    
    def get_success_url(self):
        id=self.kwargs.get("pk")
        cake_varient_object= CakeVarients.objects.get(id=id)
        cake_id=cake_varient_object.cake.id

        return reverse("cake-detail",kwargs={"pk":cake_id})


@signin_required
@is_admin
def remove_offer(request,*args,**kwargs):
    id=kwargs.get("pk")
    offer_obj=Offers.objects.get(id=id)
    cake_id=offer_obj.cakevarient.cake.id
    offer_obj.delete()
    return redirect("cake-detail",pk=cake_id)

@signin_required
def signout_view(request,*args,**kwargs):
    logout(request)
    return redirect("signin")

cakebox/templates/cakebox/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>CakeBox</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{%static 'assets/favicon.ico'%}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light">CakeBox</div>
                <div class="list-group list-group-flush">
                    <!-- <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Dashboard</a> -->
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{%url 'add-category'%}">Category Management</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{%url 'cake-add'%}">Cakes Management</a>

                    <!-- <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Status</a> -->
                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        <button class="btn btn-primary" id="sidebarToggle">Toggle Menu</button>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                                <li class="nav-item active"><a class="nav-link" href="{%url 'index'%}">Home</a></li>
                                <li class="nav-item"><a class="nav-link" href="{%url 'signout'%}">Logout</a></li>
                                <!-- <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="#!">Action</a>
                                        <a class="dropdown-item" href="#!">Another action</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#!">Something else here</a>
                                    </div>
                                </li> -->
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid">
                   {%block body_block%}
                   {%endblock%}
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>
    </body>
</html>

cakebox/templates/cakebox/cake_add.html
{%extends 'cakebox/base.html'%}

{%block body_block%}
    <div class="container d-flex flex-column align-items-center justify-content-center mt-5">
        <form action="" method="post" enctype="multipart/form-data" class=" border shadow p-5">
            <h1 class="align-items-center">Cakes</h1>

            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" value="Add">
        </form>
    </div>
{%endblock%}

cakebox/templates/cakebox/cake_detail.html
{%extends "cakebox/base.html"%}
{%block body_block%}

<div class="container">

  <div class="row">

    <div class="col-4">
      <div class="card" style="width:100%">
        <img src="{{cake.image.url}}" class="card-img-top" alt="..." height="200px">
        <div class="card-body">
          <h5 class="card-title">{{cake.name}}</h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">{{cake.name}}</li>
          <li class="list-group-item">{{cake.category}}</li>
        </ul>
        <!-- <div class="card-body">
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div> -->
      </div>
    </div>
    <div class="col-8 border boredr-dark">
      <table class="table table-striped">
        <tr>

          <td>Price</td>
          <td>Size</td>
          <td>Shape</td>
          <td>offers</td>
          <td>Action</td>
        </tr>
        {%for v in cake.cakevarients_set.all%}

        <tr>
          <td>{{v.price}}</td>
          <td>{{v.size}}</td>
          <td>{{v.shape}}</td>
          <td>
            <div class="accordion" id="accordionExample">
              <div class="accordion-item">
                <h2 class="accordion-header">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseOne{{forloop.counter}}" aria-expanded="true" aria-controls="collapseOne">
                    offers
                  </button>
                </h2>
                <div id="collapseOne{{forloop.counter}}" class="accordion-collapse collapse show"
                  data-bs-parent="#accordionExample">
                  <div class="accordion-body">


                    {%for o in v.offers_set.all%}

                    <div class="border border-top-0 border-start-0 border-end-0 border-bottom-1">
                      price:{{o.price}} start_date:{{o.start_date|date:"SHORT_DATE_FORMAT"}} |due_date :{{o.due_date|date:"SHORT_DATE_FORMAT"}}


                    </div>
                    {%endfor%}

                  </div>
                </div>
              </div>
            </div>
    </div>
    </td>

    <td>
      <a href="{%url 'update-varient' v.id %}" class="btn btn-outline-info">Edit</a>
      <a href="{%url 'remove-varient' v.id%}" class="btn btn-outline-danger">remove</a>

      <a href="{%url 'offer-varient' v.id%}" class="btn btn-outline-success">add offer</a>
    </td>
    </tr>
    {%endfor%}

    </table>
  </div>





</div>

<div class="row">
  {%for v in cake.cakevarients_set.all%}
  {%for o in v.offers_set.all%}
  <div class="border p-3">

    <div>
      size {{o.cakevarient.size}} | color {{o.cakevarient.color}}
    </div>

    <div><span>offer price$ {{o.price}}</span></div>
    <div>start_date : {{o.start_date}}</div>
    <div>due_date :{{o.due_date}}</div>
    <a href="{%url 'remove-offer' o.id%}">delete</a>
  </div>
  {%endfor%}

  {%endfor%}

</div>
{%endblock%}

cakebox/templates/cakebox/cake_edit.html
{%extends 'cakebox/base.html'%}

{%block body_block%}

    <div class="container d-flex align-items-center justify-content-center mt-5">
        <form action="" method="post" enctype="multipart/form-data" class=" border shadow p-5">
            <h1 class="align-items-center">Update Cakes</h1>
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" value="Change">
        </form>
    </div>

    {%endblock%}

cakebox/templates/cakebox/cake_list.html
{%extends 'cakebox/base.html'%}

{%block body_block%}
    <div class="container mt-5">
        <h1>Cakes</h1>
        <table class="table table-striped">
            <tr>
                <td>Category</td>
                <td>Name</td>
                <td>image</td>
                <td>Action</td>
            </tr>
            {%for ck in cakes%}

            <tr>
                <td>{{ck.category.name}}</td>
                <td>{{ck.name}}</td>
                
                <td>
                  <img src="{{ck.image.url}}" alt="" width="200px" height="200px" style="object-fit: contain;">
                </td>
                <td>
                    <a href="{%url 'cake-remove' ck.id %}" class="ms-3 text-danger"><i class="fa-solid fa-trash"></i></a>
                    <a href="{%url 'add-varient' ck.id %}" class="ms-3 text-success"><i class="fa-regular fa-square-plus"></i></a>
                    <a href="{%url 'cake-detail' ck.id%}" class="ms-3 text-warning"><i class="fa-solid fa-eye"></i></a>
                </td>
            </tr>

            {%endfor%}
        </table>
    </div>
    
{%endblock%}

cakebox/templates/cakebox/cakevar_add.html
{%extends 'cakebox/base.html'%}

{%block body_block%}

    <div class="container d-flex align-items-center justify-content-center mt-5">
        <form action="" method="post" enctype="multipart/form-data" class=" border shadow p-5">
            <h1 class="align-items-center">Add Cake Variants</h1>
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" value="Add">
        </form>
    </div>
{%endblock%}

cakebox/templates/cakebox/cakevar_edit.html
{%extends 'cakebox/base.html'%}

{%block body_block%}

    <div class="container d-flex align-items-center justify-content-center mt-5">
        <form action="" method="post" enctype="multipart/form-data" class=" border shadow p-5">
            <h1 class="align-items-center">Update Cake Variants</h1>
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" value="Change">
        </form>
    </div>
{%endblock%}

cakebox/templates/cakebox/cat_add.html
{%extends 'cakebox/base.html'%}

{%block body_block%}

    <div class="container d-flex flex-column align-items-center justify-content-center mt-5">
        <div class="border shadow p-5">
            <h1>Categories</h1>
        <div class="w-100">
            <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}}
                <input type="submit" value="Add">
            </form>
        </div>

        <div class="mt-4 w-100">
            <table class="table table-striped ">
                <tr>
                    <td>Name</td>
                    <td>Action</td>
                </tr>
    
                {%for cat in categories%}
    
                <tr>
                    <td>{{cat.name}}</td>
                <td>
                    <!-- <a href="{% url 'remove-category' cat.id%} ">Delete</a> -->
                    <a href="{%url 'remove-category' cat.id %}" class="ms-3 text-danger"><i class="fa-solid fa-trash"></i></a>

                </td>

              
                </tr>
    
                {%endfor%}
            </table>
        </div>
        </div>
    </div>

    {%endblock%}

cakebox/templates/cakebox/ck_offer.html
{%extends 'cakebox/base.html'%}

{%block body_block%}
    <div class="container">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6 mt-5">
                <form action="" method="post" enctype="multipart/form-data" class="border shadow p-5">
                    <h1 class="align-items-center">Add offer</h1>
                    {%csrf_token%}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-outline-success">Add</button>
                </form>
            </div>
            <div class="col-3"></div>
        </div>
    </div>
{%endblock%}

cakebox/templates/cakebox/index.html
{%extends "cakebox/base.html"%}
{%block body_block%}
Welcome to CakeBox


{%endblock%}

cakebox/templates/cakebox/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LOGIN PAGE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

<style>

body{
    height: 100vh;
    background-color: #4158D0;
    background-image: linear-gradient(43deg, #4158D0 0%, #C850C0 46%, #FFCC70 100%);

}

.section{
    width: 40%;
    height: 80%;
    
}


         
.btn-grad {
    background-image: linear-gradient(to right, #4776E6 0%, #8E54E9  51%, #4776E6  100%);
    margin: 10px;
    padding: 10px 45px;
    text-align: center;
    text-transform: uppercase;
    transition: 0.5s;
    background-size: 200% auto;
    color: white;            
    box-shadow: 0 0 20px #eee;
    border-radius: 10px;
    display: block;
  }

  .btn-grad:hover {
    background-position: right center; /* change the direction of the change here */
    color: #fff;
    text-decoration: none;
  }
 
</style>
</head>
<body>
    
<div class="container h-100 d-flex justify-content-center align-items-center">

  {%if messages%}
    <div class="container d-flex justify-content-center">
        <div class="w-50" style="height: 100px;">

            <div>
                {%for m in messages%}

                {%if m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>info !</strong> {{m}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>

                {%endif%}


                {%endfor%}

            </div>


        </div>

    </div>

    {%endif%}
  

    <div class="section rounded-3 bg-white p-5 shadow">
       <div class="text-center mb-5">
         <h1 class="fw-bolder">Login</h1>
       </div>
        <form action="" method="post">

          {%csrf_token%}

            <div class="mb-4">
                <label for="" class="form-label">username</label>
                <input type="text" placeholder="Type your username" class="form-control border border-start-0 border-top-0 border-end-0" name="username">
            </div>
            <div class="mb-4">
                <label for="" class="form-label">password</label>
                <input type="text" placeholder="Type your password" class="form-control border border-start-0 border-top-0 border-end-0" name="password">
            </div>
            <div>
                <button class="form-control btn-grad rounded-pill" type="submit">Login</button>
            </div>

            <div class="social-auth d-flex flex-column align-items-center">
              
                    <div>
                        <label for="">or SignUpusging</label>

                    </div>
               
                    <div>
                        <a href="">fb</a>
                        <a href="">twitter</a>
                        <a href="">google</a>
                    </div>
                    

            </div>


        </form>


    </div>

</div>


</body>
</html>